PR0030-266 reporter implementation
fobsolutions/cify-framework pull request #33
Opened 2016-12-21 13:44 UTC by vadim-fob

2016-12-21 15:57 UTC, markokonsaFob requested changes
Please do reformat the code as well, in many places the formatting is not correct (spaces are missing and so on)

2016-12-21 15:57 UTC, markokonsaFob commented on src/test/groovy/io/cify/framework/ReportingTest.groovy
> +
Unnecessary spaces

2016-12-22 08:21 UTC, vadim-fob commented
code reformated

2016-12-22 08:24 UTC, markokonsaFob approved these changes

2016-12-22 08:25 UTC, merged